/**
 * GRAMAVISE DEMO SCENARIOS / PLAYBOOK
 *
 * Pre-defined, realistic demo business input profiles for presentations and judge evaluations.
 * IMPORTANT:
 * - These are pure input sets that feed into the existing Onboarding wizard.
 * - Zero hardcoded recommendations or financial outputs.
 * - All calculations, evidence collection, scheme matching, and feasibility verdicts
 *   are deterministically generated by the active FastAPI backend.
 */

import { BusinessProfile, FinancialAssumptions } from "@/lib/types";

export interface DemoScenario {
  id: string;
  name: string;
  badge: string;
  badgeColor: string;
  category: string;
  tagline: string;
  purpose: string;
  entrepreneur: {
    fullName: string;
    phoneNumber: string;
  };
  profile: BusinessProfile;
  financials: FinancialAssumptions;
}

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: "kisan_flour_mill",
    name: "Kisan Flour Mill",
    badge: "Hero Case",
    badgeColor: "bg-emerald-100 text-emerald-800 border-emerald-300",
    category: "Flour & Spice Milling (Atta Chakki)",
    tagline: "Grain milling, flour processing & packaged spices unit",
    purpose: "Demonstrates healthy unit economics, strong debt servicing cushion, and PMEGP/MUDRA scheme alignment.",
    entrepreneur: {
      fullName: "Ramesh Kisan Patel",
      phoneNumber: "9876543210",
    },
    profile: {
      business_name: "Kisan Flour Mill",
      category: "Flour & Spice Milling (Atta Chakki)",
      description: "Modern grain milling, whole-wheat atta processing, and packaged retail spice supply for village grocery stores.",
      location: {
        state: "Maharashtra",
        district: "Pune",
        village: "Baramati",
      },
      experience_years: 5,
      own_capital: 150000,
      desired_loan: 150000,
      is_new_business: true,
    },
    financials: {
      startup_cost: 50000,
      equipment_cost: 200000,
      inventory_cost: 50000,
      monthly_fixed_cost: 20000,
      customers_per_day: 35,
      avg_ticket_price: 500,
      working_days_per_month: 26,
      variable_cost_pct: 45,
      interest_rate_pct: 10.5,
      loan_tenure_months: 60,
    },
  },
  {
    id: "lakshmi_tailoring",
    name: "Lakshmi Tailoring Centre",
    badge: "Service / Apparel",
    badgeColor: "bg-blue-100 text-blue-800 border-blue-300",
    category: "Tailoring & Garment Making",
    tagline: "Customized stitching, alterations & school uniform making",
    purpose: "Demonstrates a low-capex service enterprise with high contribution margins and MUDRA Shishu eligibility.",
    entrepreneur: {
      fullName: "Lakshmi Soundararajan",
      phoneNumber: "9840123456",
    },
    profile: {
      business_name: "Lakshmi Tailoring Centre",
      category: "Tailoring & Garment Making",
      description: "Custom ladies and children garment stitching, school uniform contracts, and embroidery alteration services.",
      location: {
        state: "Tamil Nadu",
        district: "Madurai",
        village: "Melur",
      },
      experience_years: 3,
      own_capital: 100000,
      desired_loan: 70000,
      is_new_business: true,
    },
    financials: {
      startup_cost: 20000,
      equipment_cost: 120000,
      inventory_cost: 30000,
      monthly_fixed_cost: 15000,
      customers_per_day: 8,
      avg_ticket_price: 500,
      working_days_per_month: 26,
      variable_cost_pct: 30,
      interest_rate_pct: 10.5,
      loan_tenure_months: 48,
    },
  },
  {
    id: "village_dairy",
    name: "Village Dairy Unit",
    badge: "High Debt / Risk",
    badgeColor: "bg-rose-100 text-rose-800 border-rose-300",
    category: "Dairy Farming & Milk Chilling",
    tagline: "Milch cattle procurement & bulk milk supply unit",
    purpose: "Demonstrates high fixed burden and leverage risk detection, highlighting debt-service pressure before borrowing.",
    entrepreneur: {
      fullName: "Rajesh Kumar Yadav",
      phoneNumber: "9712345678",
    },
    profile: {
      business_name: "Village Dairy Unit",
      category: "Dairy Farming & Milk Chilling",
      description: "Procurement of crossbred milch cows, fodder management, and morning/evening fresh milk collection.",
      location: {
        state: "Uttar Pradesh",
        district: "Varanasi",
        village: "Ramnagar",
      },
      experience_years: 2,
      own_capital: 80000,
      desired_loan: 300000,
      is_new_business: true,
    },
    financials: {
      startup_cost: 50000,
      equipment_cost: 250000,
      inventory_cost: 50000,
      monthly_fixed_cost: 25000,
      customers_per_day: 15,
      avg_ticket_price: 250,
      working_days_per_month: 26,
      variable_cost_pct: 65,
      interest_rate_pct: 11.0,
      loan_tenure_months: 60,
    },
  },
  {
    id: "sri_amman_tea",
    name: "Sri Amman Tea & Snacks",
    badge: "High Footfall / Micro-Ticket",
    badgeColor: "bg-amber-100 text-amber-800 border-amber-300",
    category: "Kirana & General Store",
    tagline: "Fresh tea, snacks, and morning breakfast catering stall",
    purpose: "Demonstrates volume-dependent unit economics and daily break-even threshold sensitivity in rural catchments.",
    entrepreneur: {
      fullName: "Murugan Selvam",
      phoneNumber: "9876123450",
    },
    profile: {
      business_name: "Sri Amman Tea & Snacks",
      category: "Kirana & General Store",
      description: "Daily roadside tea stall, traditional snack frying, bakery goods, and morning breakfast catering.",
      location: {
        state: "Karnataka",
        district: "Mysuru",
        village: "Nanjangud",
      },
      experience_years: 4,
      own_capital: 60000,
      desired_loan: 100000,
      is_new_business: true,
    },
    financials: {
      startup_cost: 25000,
      equipment_cost: 100000,
      inventory_cost: 25000,
      monthly_fixed_cost: 18000,
      customers_per_day: 40,
      avg_ticket_price: 50,
      working_days_per_month: 26,
      variable_cost_pct: 55,
      interest_rate_pct: 10.5,
      loan_tenure_months: 48,
    },
  },
];
